# Generated by Django 6.0.7 on 2026-07-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('anno', models.IntegerField()),
                ('targa', models.CharField(max_length=20, unique=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='auto/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=30)),
                ('patente', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=100)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritiro', models.DateTimeField()),
                ('riconsegna', models.DateTimeField()),
                ('creata_il', models.DateTimeField(auto_now_add=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.cliente')),
            ],
        ),
    ]
